#SUBSCRIBED https://raw.githubusercontent.com/arthur97172/Rule_script/main/Stash/subscription.yaml
proxy-providers:
  AirPort-1:
    type: http
    interval: 86400
    url: https://clash0811-main.rss-node.com/sub?target=clash&interval=129600&filename=Hitun&url=https%3A%2F%2Frss-node.com%2Flink%2FO3Nv53oivnWksQdV%3Fmu%3D1
mode: rule
dns:
  default-nameserver:
    - 223.5.5.5
    - 119.28.28.28
    - system
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
proxies: []
proxy-groups:
  - name: 默认节点
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Proxy.png
    proxies:
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
      - 直连
  - name: OpenAI
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/OpenAI_1.png
    proxies:
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
  - name: Gemini
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png
    proxies:
      - US 美国
      - 其它地区
      - TW 台湾
  - name: Google
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Google_Search.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: Twitter
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Twitter.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: YouTube
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/YouTube.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
      - IN 印度
  - name: NETFLIX
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Netflix.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: Disney+
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Disney+.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: HBOMax
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/HBO_Max.png
    proxies:
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
  - name: Telegram
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Telegram.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: Spotify
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Spotify.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: TikTok
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/TikTok.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: Steam
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Steam.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: Apple
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Apple.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
      - 直连
  - name: Microsoft
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Microsoft.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: GitHub
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/GitHub.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: LinkedIn
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Linkedin.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: 哔哩东南亚
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/bilibili.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: 巴哈姆特
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Bahamut.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
  - name: 国内网站
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Streaming!CN.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
      - DIRECT
  - name: 其他外网
    type: select
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/Area.png
    proxies:
      - 默认节点
      - HK 香港
      - TW 台湾
      - JP 日本
      - KR 韩国
      - US 美国
      - SG 新加坡
      - 其它地区
      - DIRECT
  # 基于地区分组
  - name: HK 香港
    type: url-test
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/HK.png
    include-all: true
    interval: 120
    tolerance: 50
    filter: "(?i)(澳门|🇲🇴|港|🇭🇰|hk|hong)"
  - name: TW 台湾
    type: url-test
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/TW.png
    include-all: true
    interval: 120
    tolerance: 50
    filter: "(?i)(台|🇹🇼|湾|tw|taiwan)"
  - name: JP 日本
    type: url-test
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/JP.png
    include-all: true
    interval: 120
    tolerance: 50
    filter: "(?i)(日|🇯🇵|东京|大阪|jp|japan)"
  - name: KR 韩国
    type: url-test
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/KR.png
    include-all: true
    interval: 120
    tolerance: 50
    filter: "(?i)(韩|🇰🇷|kr|korea)"
  - name: US 美国
    type: url-test
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/US.png
    include-all: true
    interval: 120
    tolerance: 50
    filter: "(?i)(美|🇺🇲|us|states|america)"
  - name: SG 新加坡
    type: url-test
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/SG.png
    include-all: true
    interval: 120
    tolerance: 50
    filter: "(?i)(新加坡|坡|狮城|🇸🇬|sg|singapore)"
  - name: IN 印度
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/India.png
    include-all: true
    tolerance: 50
    filter: "(?i)(india|in\\b|ind\\b|印度)"
  - name: 其它地区
    type: url-test
    icon: https://raw.githubusercontent.com/arthur97172/Rule_script/main/Iconset/World_Map.png
    include-all: true
    interval: 120
    tolerance: 50
    filter: "(?i)^(?!.*(?:🇭🇰|🇹🇼|🇯🇵|🇰🇷|🇺🇸|🇸🇬|🇨🇳|港|hk|hong|台|tw|taiwan|日本|jp|japan|韩|kr|korea|美|us|states|新加坡|sg|singapore|防失联|入门无)).*"
  - name: 直连
    type: select
    proxies:
      - DIRECT
rules:
  - RULE-SET,HBOMax,HBOMax
  - RULE-SET,Gemini,Gemini
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,Telegram,Telegram
  - RULE-SET,biliintl,哔哩东南亚
  - RULE-SET,bahamut,巴哈姆特
  - RULE-SET,youtube,YouTube
  - RULE-SET,Twitter,Twitter
  - RULE-SET,netflix,NETFLIX
  - RULE-SET,github,GitHub
  - RULE-SET,linkedin,LinkedIn
  - RULE-SET,spotify,Spotify
  - RULE-SET,disney,Disney+
  - RULE-SET,tiktok,TikTok
  - RULE-SET,steam_cn,国内网站
  - RULE-SET,steam,Steam
  - RULE-SET,pixiv,其他外网
  - RULE-SET,google-cn,Google
  - RULE-SET,apple-cn,Apple
  - RULE-SET,microsoft_cn,国内网站
  - RULE-SET,microsoft,Microsoft
  - GEOIP,LAN,直连
  - GEOIP,CN,国内网站
  - MATCH,其他外网
rule-providers:
  Telegram:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.list
  biliintl:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/biliintl.list
  bahamut:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/bahamut.list
  youtube:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.list
  netflix:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/netflix.list
  spotify:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.list
  disney:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/disney.list
  tiktok:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/tiktok.list
  steam_cn:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam@cn.list
  steam:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam.list
  pixiv:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/pixiv.list
  google-cn:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google-cn.list
  apple-cn:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple-cn.list
  microsoft_cn:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft@cn.list
  microsoft:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.list
  github:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/github.list
  linkedin:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/linkedin.list
  Twitter:
    type: http
    behavior: domain
    interval: 864000
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/twitter.list
    format: text
  OpenAI:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/openai.list
  Gemini:
    type: http
    behavior: classical
    format: yaml
    interval: 86400
    url: https://raw.githubusercontent.com/joeblack69/Clash-config-rule/refs/heads/main/Rule/Gemini.yaml
  HBOMax:
    type: http
    behavior: classical
    format: yaml
    interval: 86400
    url: https://raw.githubusercontent.com/joeblack69/Clash-config-rule/refs/heads/main/Rule/HBOMax.yaml